language: rust
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - libssl-dev

rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
script:
  - cargo clean
  - cargo build
  - cargo test --package courier

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo run --package courier -- run &
    cargo tarpaulin --ignore-tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
