sudo: required
dist: xenial
addons:
    apt:
        packages:
            - libssl-dev

language: rust
rust:
  - nightly
cache: cargo

script:
  - cargo clean
  - cargo build
  - cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ignore-tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
