language: rust
sudo: required
dist: xenial
addons:
    apt:
        packages:
            - libssl-dev

rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt-preview
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo fmt --all -- --check
  - cargo clean
  - cargo build
  - cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ignore-tests --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
