[workspace]

members = [
    "service",
    "clients/rust"
]

[dependencies]
chrono = {version = "0.4.4",features = ["serde"]}
parking_lot = "0.6.2"
serde = "1.0.68"
serde_derive = "1.0.68"
serde_json = "1.0.22"
