[package]
name = "qorier"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.1.19"
gotham = "0.2.0"
hyper = "0.11.22"
mime = "0.3.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.6", features = ["serde", "v4"] }

[lib]
name = "qorier"
path = "src/lib.rs"

[[bin]]
name = "qorier"
path = "src/main.rs"
