[package]
name = "courier"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
description = "A simple pubsub service."
license = "(MIT OR Apache-2.0)"

[dependencies]
actix = "0.5.8"
actix-web = { git = "https://github.com/davidMcneil/actix-web", branch = "0.6" }
chrono = {version = "0.4.4",features = ["serde"]}
env_logger = "0.5.10"
futures = "0.1"
open = "1.2.1"
parking_lot = "0.6.2"
psutil = "1.1.1"
rand = "0.5.2"
reqwest = "0.8.6"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.21"
structopt = "0.2.10"
uuid = {version = "0.6.5",features = ["serde","v4"]}

[lib]
name = "courier"
path = "src/lib.rs"

[[bin]]
name = "courier"
path = "src/main.rs"
