[package]
name = "qorier"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = { version = "0.6", features = ["serde", "v4"] }
