[package]
name = "courier"
version = "0.1.0"
authors = ["David McNeil <mcneil.david2@gmail.com>"]
description = "A simple pubsub service."
license = "MIT/Apache-2.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
psutil = "1.1.1"
rand = "0.4.2"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
rocket_cors = "0.2.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2.7"
uuid = { version = "0.6", features = ["serde", "v4"] }

[lib]
name = "courier"
path = "src/lib.rs"

[[bin]]
name = "courier"
path = "src/main.rs"
